repos:
  - repo: local
    hooks:
      - id: lint
        name: npm run lint
        entry: npm run lint
        language: system
        pass_filenames: false
      - id: format
        name: npm run check:format
        entry: npm run check:format
        language: system
        pass_filenames: false
      - id: typecheck
        name: npm run check:types
        entry: npm run check:types
        language: system
        pass_filenames: false
